// Minimal config files gaiad needs to start: a cometbft config.toml,
// a cosmos-sdk app.toml, and a client.toml. Values are tuned for an
// offline-state-sync bootstrap scenario (state-sync disabled,
// block-sync enabled, sensible mempool/peer defaults).

package bootstrap

import (
	"fmt"
	"os"
	"path/filepath"
)

func writeConfigFiles(root, moniker, appDB, cmtDB string) error {
	cfgDir := filepath.Join(root, "config")
	if err := os.MkdirAll(cfgDir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(cfgDir, "config.toml"),
		[]byte(renderConfigTOML(moniker, cmtDB)), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(cfgDir, "app.toml"),
		[]byte(renderAppTOML(appDB)), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(cfgDir, "client.toml"),
		[]byte(renderClientTOML()), 0o644); err != nil {
		return err
	}
	return nil
}

func renderConfigTOML(moniker, dbBackend string) string {
	return fmt.Sprintf(`# Generated by malcom bootstrap. Minimal cometbft config.
proxy_app = "tcp://127.0.0.1:26658"
moniker = %q
db_backend = %q
db_dir = "data"
log_level = "info"
log_format = "plain"
genesis_file = "config/genesis.json"
priv_validator_key_file = "config/priv_validator_key.json"
priv_validator_state_file = "data/priv_validator_state.json"
priv_validator_laddr = ""
node_key_file = "config/node_key.json"
abci = "socket"
filter_peers = false

[rpc]
laddr = "tcp://127.0.0.1:26657"
cors_allowed_origins = []
cors_allowed_methods = ["HEAD", "GET", "POST"]
cors_allowed_headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time"]
grpc_laddr = ""
grpc_max_open_connections = 900
unsafe = false
max_open_connections = 900
max_subscription_clients = 100
max_subscriptions_per_client = 5
experimental_subscription_buffer_size = 200
experimental_websocket_write_buffer_size = 200
experimental_close_on_slow_client = false
timeout_broadcast_tx_commit = "10s"
max_request_batch_size = 10
max_body_bytes = 1000000
max_header_bytes = 1048576
tls_cert_file = ""
tls_key_file = ""
pprof_laddr = ""

[p2p]
laddr = "tcp://0.0.0.0:26656"
external_address = ""
seeds = ""
persistent_peers = ""
addr_book_file = "config/addrbook.json"
addr_book_strict = true
max_num_inbound_peers = 40
max_num_outbound_peers = 10
unconditional_peer_ids = ""
persistent_peers_max_dial_period = "0s"
flush_throttle_timeout = "100ms"
max_packet_msg_payload_size = 1024
send_rate = 5120000
recv_rate = 5120000
pex = true
seed_mode = false
private_peer_ids = ""
allow_duplicate_ip = false
handshake_timeout = "20s"
dial_timeout = "3s"

[mempool]
type = "flood"
recheck = true
recheck_timeout = "1s"
broadcast = true
wal_dir = ""
size = 5000
max_txs_bytes = 1073741824
cache_size = 10000
keep-invalid-txs-in-cache = false
max_tx_bytes = 1048576
max_batch_bytes = 0
experimental_max_gossip_connections_to_persistent_peers = 0
experimental_max_gossip_connections_to_non_persistent_peers = 0

[statesync]
enable = false
rpc_servers = ""
trust_height = 0
trust_hash = ""
trust_period = "168h0m0s"
discovery_time = "15s"
temp_dir = ""
chunk_request_timeout = "10s"
chunk_fetchers = "4"

[blocksync]
version = "v0"

[consensus]
wal_file = "data/cs.wal/wal"
timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "5s"
double_sign_check_height = 0
skip_timeout_commit = false
create_empty_blocks = true
create_empty_blocks_interval = "0s"
peer_gossip_sleep_duration = "100ms"
peer_query_maj23_sleep_duration = "2s"

[storage]
discard_abci_responses = false

[tx_index]
indexer = "null"

[instrumentation]
prometheus = false
prometheus_listen_addr = ":26660"
max_open_connections = 3
namespace = "cometbft"
`, moniker, dbBackend)
}

func renderAppTOML(dbBackend string) string {
	return fmt.Sprintf(`# Generated by malcom bootstrap. Minimal cosmos-sdk app config.

###############################################################################
###                           Base Configuration                            ###
###############################################################################

minimum-gas-prices = "0.0025uatom"
pruning = "default"
pruning-keep-recent = "0"
pruning-interval = "0"
halt-height = 0
halt-time = 0
min-retain-blocks = 0
inter-block-cache = true
index-events = []
iavl-cache-size = 781250
iavl-disable-fastnode = false
app-db-backend = %q

###############################################################################
###                         Telemetry Configuration                         ###
###############################################################################

[telemetry]
service-name = ""
enabled = false
enable-hostname = false
enable-hostname-label = false
enable-service-label = false
prometheus-retention-time = 0
global-labels = []

###############################################################################
###                           API Configuration                             ###
###############################################################################

[api]
enable = false
swagger = false
address = "tcp://localhost:1317"
max-open-connections = 1000
rpc-read-timeout = 10
rpc-write-timeout = 0
rpc-max-body-bytes = 1000000
enabled-unsafe-cors = false

###############################################################################
###                           gRPC Configuration                            ###
###############################################################################

[grpc]
enable = true
address = "localhost:9090"
max-recv-msg-size = "10485760"
max-send-msg-size = "2147483647"

[grpc-web]
enable = true

###############################################################################
###                         State Sync Configuration                        ###
###############################################################################

[state-sync]
snapshot-interval = 0
snapshot-keep-recent = 2

###############################################################################
###                              Wasm                                       ###
###############################################################################

[wasm]
simulation_gas_limit = ""
query_gas_limit = 3000000
memory_cache_size = 100
contract_debug_mode = false
`, dbBackend)
}

func renderClientTOML() string {
	return `# Generated by malcom bootstrap. Minimal client config.
chain-id = ""
keyring-backend = "test"
output = "text"
node = "tcp://localhost:26657"
broadcast-mode = "sync"
`
}
